### ISSUE TITLE
smtp authentication 

### ISSUE THREAD

**Issue by masihfathi** [zytzagoo/smtp-validate-email#14]
I want to write a script to validate a list with multi smtp, How i can connect  smtp server with authentication ( I mean host, user, password and email)?

**Comment by zytzagoo** [comment]
Not supported out of the box currently. 

The code to support it should not be that complicated.
Maybe look at PHPMailer or similar libraries for inspiration and contribute back if/when you build it!

**Comment by haffoudhi** [comment]
anyone has the smtp authentication working with this code ?

**Comment by haffoudhi** [comment]
i m confused about something, without authentication the code will connect the socket to receiver host directly, which in some hosts is not permitted, you need to login first then send emails. So we can't connect to receiver host with socket, we need to connect to sender host with socket. 
My question: is it possible to validate emails in such case when we can't use socket to connect to another host directly ?
