### ISSUE TITLE
not working on port 465 or 587

### ISSUE THREAD

**Issue by ahsanic** [zytzagoo/smtp-validate-email#15]
Connect failed: Network is unreachable, error number: 101, host: gmail-smtp-in.l.google.com:465

**Comment by zytzagoo** [comment]
Error message seems quite clear (looks like a general connectivity issue).
Can you successfully connect (from the same machine) without going through php?

I vaguely remember gmail requiring tls on port 587, but it might not be related at all...

**Comment by ahsanic** [comment]
So the problem was port 25, it was blocked! 
Thanks anyway.
