### ISSUE TITLE
How to read the result as valid or invalid.

### ISSUE THREAD

**Issue by Wmas** [zytzagoo/smtp-validate-email#17]
75% of the tested email addresses (existing and correct, existing but incorrect) gives the same $smtp_results array (except the address of course). 

I have tried to use the $smtp_results[$email] which in some cases when the email address is correct will be equal to 1:

```
Array
(
    [info@entrustrock.nl] => 1
    [domains] => Array
        (
            [entrustrock.nl] => Array
                (
                    [users] => Array
                        (
                            [0] => info
                        )

                    [mxs] => Array
                        (
                            [entrustrock.nl] => 0
                        )

                )

        )

)
```

But as described here above with some others correct addresses it will be empty and it will flag it as incorrect. 

Can you please add in the read me file an example which will describe how we can use the returned array to detect if an email address is valid on invalid?

Regards

**Comment by nicolasguzca** [comment]
+1

**Comment by zytzagoo** [comment]
I'm having a hard time understanding the question... 

If/when `$smtp_results[$email]` does not equal a *truthy* value, it means that email is considered invalid for whatever reason (there could be many reasons). 

You can try setting `public debug = true;` within the class (https://github.com/zytzagoo/smtp-validate-email/blob/master/smtp-validate-email.php#L83) or just do `$validator->debug = true;` before calling `validate()`.

That way you'll hopefully see exactly what happens and how/why an address ends up being marked as (in)valid.

Does that help?

**Comment by Wmas** [comment]
Thank you for your reply.

I will give it a try

Regards

Franco Magliozzi
franco@webline-studio.nl

**Comment by dmorri** [comment]
Any luck determining when Yahoo.com (or other domains that do the same thing) emails are valid or not. It just sends back valid for ANYTHING. I have seen sites that seem to get it right like: http://www.email-validator.net

**Comment by dmorri** [comment]
For example dmorrixyz@yahoo.com is invalid, but dmorri@yahoo.com is valid. But both come back Valid.
