### ISSUE TITLE
Fatal error when remote closed the connection.

### ISSUE THREAD

**Issue by kn007** [zytzagoo/smtp-validate-email#27]
```
<?php

require('smtp-validate-email.php');

$from = 'admin@126.com'; // for SMTP FROM:<> command
$email = 'admin@ikx.me';

$validator = new SMTP_Validate_Email($email, $from);
$smtp_results = $validator->validate();

var_dump($smtp_results);
```

Result:

```
PHP Fatal error:  Uncaught SMTP_Validate_Email_Exception_No_Connection: No connection in /tmp/smtp-validate-email.php:632
Stack trace:
#0 /tmp/smtp-validate-email.php(498): SMTP_Validate_Email->send('EHLO kn007.net')
#1 /tmp/smtp-validate-email.php(466): SMTP_Validate_Email->ehlo()
#2 /tmp/smtp-validate-email.php(284): SMTP_Validate_Email->helo()
#3 -(9): SMTP_Validate_Email->validate()
#4 {main}
  thrown in /tmp/smtp-validate-email.php on line 632
```

I think it should return false.

Same error when remote address is www.dgpt.edu.cn. (timeout)

Any plan to add new parameter for timeout?

**Comment by zytzagoo** [comment]
Catch the specific exception in your code, and return false in that case (you create a wrapper function which calls the code above and returns what you want). 

Same goes for the timeout case/exception too really?

Or I'm not understanding what's really bothering you... What would the parameter do specifically that your wrapper function cannot do?

Adding another param just complicates things, especially so if it would change the current/default behavior...

If you have an idea for a parameter and how it would/should work, maybe do a pull request for it and we can see it in action?

**Comment by kn007** [comment]
Sorry, this is my fault. The code is working properly. Thank you.
