### ISSUE TITLE
How does this code, works?

### ISSUE THREAD

**Issue by anandkumar321** [zytzagoo/smtp-validate-email#42]
Hi,

I have installed it and can access it in browser. But I cant see any results. Where I will see if the email ids are bounced or correct?

**Comment by zytzagoo** [comment]
It's a library, you have to write some code of your own in order to be able to use it however you want...

Readme contains a basic example: https://github.com/zytzagoo/smtp-validate-email#basic-example

You can also look at the tests code to see how things work generally...
