### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ip-to-geolocation** [zytzagoo/smtp-validate-email#48]
I have precisely followed the instructions, installed with composer, and created a PHP file containing a copy past of the first exemple, on a freshly installed centos 7.

i get this output:

<b>Parse error</b>:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in <b>/var/www/html/vendor/zytzagoo/smtp-validate-email/src/Validator.php</b> on line <b>982</b><br />	

Any suggestions ?

thanks a lot

**Comment by zytzagoo** [comment]
Which version did you install? Do you have composer install log/output saved somewhere maybe?

Line 982 does not contain the "class" keyword at all: 
master: https://github.com/zytzagoo/smtp-validate-email/blob/master/src/Validator.php#L982
v1.0: https://github.com/zytzagoo/smtp-validate-email/blob/v1.0.0/src/Validator.php#L982

(incidentally, v0.7 does not even have L982...)

Without more details, it's really hard to say anything conclusive at this point...
