### ISSUE TITLE
Getting No connection error

### ISSUE THREAD

**Issue by rvigneshw** [zytzagoo/smtp-validate-email#61]
`{"info@customdomain.com":{"result":0,"info":"no connection"}}`

I'm using this library in laravel app but unable to any verification with this

**Comment by zytzagoo** [comment]
How exactly are you using it? What does the log contain (see getLog() method)?

**Comment by rvigneshw** [comment]
If someone looking for solution, It's not the library error.

It's mainly due to your ISP blocking port 25, Read here: https://www.authsmtp.com/faqs/faq-4.html

What I did was to spin off a instance on any cloud provider and ssh into it and ran it and it did worked pretty well.
