### ISSUE TITLE
Call to a member function format() on bool in zytzagoo\smtp-validate-email\src\Validator.php on line 942.

### ISSUE THREAD

**Issue by tobiascapin** [zytzagoo/smtp-validate-email#69]
Call to a member function format() on bool in C:\Users\Tobia\git\cinebot\SitoTicketing\vendor\zytzagoo\smtp-validate-email\src\Validator.php on line 942.

`$date = \DateTime::createFromFormat('U.u', sprintf('%.f', microtime(true)))->format('Y-m-d\TH:i:s.uO');`

This error is related to the decimal separator of the system. If it is other than "." it fails.

It should be replaced with:

`$date = \DateTime::createFromFormat('U.u', number_format(microtime(true), 6, '.', ''))->format('Y-m-d\TH:i:s.uO');`

**Comment by zytzagoo** [comment]
Hi, thanks for the report. 
Current master/main source has something else on L942: https://github.com/zytzagoo/smtp-validate-email/blob/master/src/Validator.php#L942 -- which version are you running exactly? Do you have some (hopefully) reduced example/test-case that demonstrates the issue reliably?

After seeing the example you edited, this looks related to #58 and was fixed with #59 ?

**Comment by zytzagoo** [comment]
I guess you're using via composer with 1.0.0 probably? Can you switch to dev-master and see if it fixes the issue?

Or you can wait for the next release, which will happen when time permits.
Need to remember how I did these things... (also probably need to see what is sitting/waiting for the release (https://github.com/zytzagoo/smtp-validate-email/blob/master/CHANGELOG.md) and decide on version numbering and whatnot...bleh)

**Comment by tobiascapin** [comment]
Hi, I have used the version downloaded from composer. I looks like the 1.0.
The problem seems to be the same linked, I will try downloading from here the last version.
Thanks

**Comment by zytzagoo** [comment]
Download manually, or just set version in composer to 'dev-master' and it should grab/install latest master as opposed to latest "stable".

**Comment by tobiascapin** [comment]
Yes, with dev-master it works. No more errors. Thank you very much.
