### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by NetaliDev** [zytzagoo/smtp-validate-email#76]
The PR with the locale issue fixes has been merged nearly two years ago and it would be nice to have this patch available in composer without using "dev-master" as the version. So a version bump would be nice.

**Comment by zytzagoo** [comment]
I agree, it's been too long -- will try to tag 1.1.0 this week.

Would also be great to get more feedback in the meantime (regarding changes that landed recently). The changes are supposed to be backwards-compatible, but who knows...
