### ISSUE TITLE
Improving performance & question about catch-all checks

### ISSUE THREAD

**Issue by kriiv** [zytzagoo/smtp-validate-email#79]
Hi!
Amazing work with the package.

Currently average verification request time is between 2-2.5 seconds.
Is there a way to shorten this? 

With regards to checking catch-all, I can see the readme mentioned catch-all checking but I don't see the debug log or response providing any information on catch-all status. How can I go about accessing the response data for these checks?

**Comment by zytzagoo** [comment]
Turn on debug logging and examine timestamps in output.. that may help you pinpoint where exactly the slowness comes from.

Library version may also play a part in this, depending on how your dns is set up. Which exact version are you using?
